### ISSUE TITLE
Suggestion to updage the docs regarding the game's pre-reqs needing outside installation

### ISSUE THREAD

**Issue by nonplayer** [Raziel7893/WindowsGSM.KingdomOfAtham#1]
My first attempts to get this working on a dedicated server machine were failures. Turns out that the game requires Microsoft Visual C++ 2015-2022 runtime as a pre-req to run. I kept getting exit code -1073741515 when trying to launch the game. If you are trying to get this running on a dedicated WindowsGSM server that does not have Steam on it, you'll either need to download and install that manually first, or install steam, install the base game, and launch it - the requirements will install on the actual game's first run.

**Comment by Raziel7893** [comment]
thought it was common knowledge that on steam games the prerequesits are delivered with the serverfiles. 
just click Browse => Server files, go to _CommonRedist and install everything in there even if you think you already have it.

but will add it to the readme :)

**Comment by nonplayer** [comment]
Honestly you're probably right, this is just the first time I've encountered it. I've been running several SteamCMD games off this dedicated server, this was the first one that needed outside pre-reqs.

Anyway thanks again for the plugin, it works perfectly!

**Comment by Raziel7893** [comment]
No problem, always good to add those things to the readme.

Happy it works :)
